sudo: required
dist: trusty

services:

language: cpp

install: |
  set -x
  CCTOOLS_VER=5.4.17
  mkdir -p /tmp/cctools
  pushd /tmp/cctools
    curl -O http://ccl.cse.nd.edu/software/files/cctools-$CCTOOLS_VER-source.tar.gz
    tar xzf *.tar.gz
    cd cctools*
    ./configure --prefix /usr
    make -j$(grep -c bogomips /proc/cpuinfo) > /dev/null 2>&1
    sudo make install > /dev/null 2>&1
  popd
  work_queue_worker --help
  mkdir build
  pushd build
    cmake .. -DCMAKE_INSTALL_PREFIX=/usr \
             -DCCTOOLS=/usr
    make -j$(grep -c bogomips /proc/cpuinfo)
    sudo make install
  popd
  which alien_wq_worker.sh

script: |
  set -ex
  cd /
  printf '#!/bin/bash -e\necho this is a ${ALIEN_TEST_VARIABLE}${FILTERED_OUT}\n' > /tmp/job.sh
  chmod +x /tmp/job.sh
  WQ_NUM_FOREMEN=3 alien_wq_worker.sh start-foremen
  WQ_NUM_WORKERS=5 alien_wq_worker.sh start-workers
  sleep 5
  [[ $(alien_wq_worker.sh count-foremen) == 3 ]]
  [[ $(alien_wq_worker.sh count-workers) == 5 ]]
  set +x
  export AWQ_WORKDIR=/tmp/awq_test
  for CMD in "alien_work_queue --job-wrapper /usr/etc/alien_job_wrapper.sh --work-dir $AWQ_WORKDIR" \
             "alien_work_queue --work-dir $AWQ_WORKDIR"; do
    OK=
    echo "==> Testing $CMD"
    [[ "$CMD" == *wrapper* ]] && EXPECT='this is a test' || EXPECT='this is a testyabba'
    ps aux | grep -v grep | grep work_queue || true
    rm -f /tmp/job.out
    printf 'executable = /tmp/job.sh\noutput = /tmp/job.out\nenvironment = ALIEN_TEST_VARIABLE=test;FILTERED_OUT=yabba\n' | condor_submit
    $CMD &
    for ((I=0; I<40; I++)); do
      echo "Waiting for results of $CMD since $I seconds"
      [[ $(cat /tmp/job.out 2> /dev/null || true) == "$EXPECT" ]] && { echo "OK (expecting \"$EXPECT\")"; OK=1; break; } || sleep 1
    done
    [[ $OK == 1 ]] && { killall -KILL alien_work_queue; continue; } || true
    echo "Job output for $CMD does not match expectations ($EXPECT), generated output:"
    cat /tmp/job.out || true
    false
  done
  echo "==> Testing catalog server"
  set -x
  printf "#!/bin/bash -e\nsleep 1000\n" > /tmp/job.sh
  printf "executable = /tmp/job.sh\noutput = /tmp/job.out\n" | condor_submit
  alien_work_queue --work-dir $AWQ_WORKDIR --catalog-host localhost --catalog-port 9097 &
  catalog_server --update-host=do-not-update-please --history=/tmp/catalog.history/ &
  set +x
  OK=
  for ((I=0; I<100; I++)); do
    echo "Waiting for catalog server update since $I seconds"
    (curl -sq http://localhost:9097/query.text 2> /dev/null || true) | grep -q "project alien_jobs" \
      && { echo "Catalog OK!"; OK=1; break; } || sleep 1
  done
  [[ $OK == 1 ]] || { echo "Project not registered to the catalog! Output of catalog query:"; \
                      ( curl http://localhost:9097/query.text || true ); false; }
  echo "All tests successful!"
